### ISSUE TITLE
Variables for order data? name, qty, sku etc?

### ISSUE THREAD

**Issue by lovelife85** [thiagolima-bm/magento-csvexport#1]
Hi, great extension! Unable to get the order data variables in the export csv.

I tried these variables but the cells remain empty: {{var items}};{{var product_name}}

Thank you in advance
Regards

**Comment by thiagolima-bm** [comment]
Hi, @lovelife85. Unfortunately, is not possible to iterate using the template parser at Magento 1. Event in Magento 2 hehe. I had to create a pull request to create this functionality. 

https://github.com/magento/magento2/pull/9401

The solution is to override the class lib/Varien/Filter/Template.php

You can copy the solution for M2, the class is pretty much the same.

Cheers

**Comment by lovelife85** [comment]
Hi, thank you for replying. I am actually using magento 1.9.3.6. Other variables like first name and street are showing correctly in orders.csv

So in orders>template I add: {{var item.sku}} or do i write this up differently?

Thanks

**Comment by thiagolima-bm** [comment]
@lovelife85 the point is: you cannot iterate.
you should be able to do something like this:

`{{loop order.all_visible_items}}
            <li>
                sku: {{var item.sku}}<br>
                name: {{var item.name}}<br>
                price: {{var item.price}}<br>
                quantity: {{var item.ordered_qty}}<br>
            </li>
{{/loop}}`

but you can not.

What you can do is create a new view and use union to create your report 

e.g.:
`SELECT 	
	entity_id,
	increment_id,
	'' AS sku,
	'' AS price
FROM 
	sales_flat_order
UNION ALL
SELECT 	
	entity_id,
	'' AS increment_id,
	sku,
	price
FROM 
	sales_flat_order o
LEFT JOIN
	sales_flat_order_item i ON o.entity_id = i.order_id
ORDER BY entity_id`

**Comment by lovelife85** [comment]
Oh man, I dont have a clue how to do this...I tried to generate this: {{var order.item.sku}};{{var order.item.name}};{{var order.item.ordered_qty}}

**Comment by thiagolima-bm** [comment]
@lovelife85 I see. Well, by the end of the week I could create a hotfix for this :P

**Comment by lovelife85** [comment]
That would be awesome cause it would make your extension complete showing all order customer info + order data. I guess most crucial would be: sku, productname, quantity right?

**Comment by thiagolima-bm** [comment]
New functionality created.
Now you are able to use something like this: 

`{{for item in order.all_visible_items}}
                index: {{var loop.index}}
                sku: {{var item.sku}}
                name: {{var item.name}}
                price: {{var item.price}}
                quantity: {{var item.ordered_qty}}
        {{/for}}
 `

**Comment by thiagolima-bm** [comment]
Fix applied :)
